### ISSUE TITLE
issue about text

### ISSUE THREAD

**Issue by Lzw104522773** [11jo/Paladins-of-Faerun-Quest-Pack#4]
I opened XGBOOKP.tra in a Chinese Windows environment and it displayed as follows:
![image](https://github.com/user-attachments/assets/9d5b2669-01e7-43b5-854d-94f0052deb06)

**Comment by 11jo** [comment]
Hello !

Yeah, this files is special it is not meant to be translated, it's only a list of moddeur, betatesteur like credits or tribute to those who participated to the creation of the mod. 

But yes it's possible that it will be a problem for your language or other, I am not sure I will let it implemented.


@Lzw104522773, Paladins of Faerun is in progress, I actually still work on tra files for every languages and it's not a good idea to translate it yet. I have to move around some streff in tra file (For journal entries mostly).

Few lines are concerned, but they are scattered in many files.

So if it's the same for you to wait until I finish to deal with translation files.


Also, I don't know what language you use for your translation, but be aware the english translation of the mod is innacurate, and really bad. 
English should not be used for translation... 

(I currently use Russian and English for translate the mod into french but mostly I look what happen in game to have an accurate and logical translation)

I plan to ask on the forums if someone want to do a very big proofreading of english language as soon I finish to implement regular journal entries.

**Comment by Lzw104522773** [comment]
Okay, I understand. I'll wait for you to finish handling it. I translate from English to Chinese.
