### ISSUE TITLE
Issue about item description text @ 719

### ISSUE THREAD

**Issue by Lzw104522773** [11jo/Paladins-of-Faerun-Quest-Pack#5]
I started translating ‘Paladins-of-Faerun-Quest-Pack’.

SETUP-PoFQuestPack.tra，

@ 719, the 'Urgoth' attribute description for 'Power 3 times a day' should have 'Power' as the spell 'Strength'. I added this item by console in the game and used this ability. The game prompt shows the effect is the spell 'Strength'.

**Comment by Lzw104522773** [comment]
SETUP-PoFQuestPack.tra

@1202   = ~Negative Energy Beam ~

@1203   = ~Negative Energy Beam  
According to the spell effect description, ‘Negative Energy Beam’ should be 'Negative Energy Explosion'.

@532:
Beam of Negative Energy 3 times per day
Explosion of Negative Energy 2 times per day
 

‘Beam of Negative Energy’ = ‘Negative Energy Beam’ ?

'Explosion of Negative Energy' =  'Negative Energy Explosion' ?

**Comment by Lzw104522773** [comment]
SETUP-PoFQuestPack.tra
 

issue about:

@1625 = ~Please follow the stairs behind me, you are awaited my lord...~ ~Please follow the stairs behind me, you are awaited milady...~
Maybe:
@1625 = ~Please follow the stairs behind me, you are awaited <PRO_LADYLORD>...~

**Comment by 11jo** [comment]
I am not sure I understand the issue...

Did you read my response to your [previous message here](https://github.com/11jo/Paladins-of-Faerun-Quest-Pack/issues/4#issuecomment-2232881189) ?

> @Lzw104522773, Paladins of Faerun is in progress, I actually still work on tra files for every languages and it's not a good idea to translate it yet. I have to move around some streff in tra file (For journal entries mostly).
> 
> Few lines are concerned, but they are scattered in many files.
> 
> So if it's the same for you to wait until I finish to deal with translation files.
> 
> Also, I don't know what language you use for your translation, but be aware the english translation of the mod is innacurate, and really bad. English should not be used for translation...
> 
> (I currently use Russian and English for translate the mod into french but mostly I look what happen in game to have an accurate and logical translation)
> 
> I plan to ask on the forums if someone want to do a very big proofreading of english language as soon I finish to implement regular journal entries.

And your answer....

> Okay, I understand. I'll wait for you to finish handling it. I translate from English to Chinese.



The mod is **_`not ready to translate in another langage`_** because I still have some modification ongoing on the tra files and the **`english translation is innacurate and should not be used for translation`.**

**Comment by Lzw104522773** [comment]
Sorry, I forgot. Let me pause the translation.

**Comment by 11jo** [comment]
I'll leave the issue open (as reminder for me) to let you know when it's possible to start translating.

Unfortunately, I can't give you a deadline yet.

In any case, until someone proofreads the English translation, it will remain totally inaccurate.

**Comment by Lzw104522773** [comment]
OK. To achieve accurate translation is quite time-consuming, and I know the hardships involved. You've worked hard, come on!
